package equals;

import java.util.Objects;

public class Address {
    public static void main(String[] args) {
        Address address1 = new Address("Russia", "Lorina street", 32);
        Address address2 = new Address("Russia", "Lorina street", 32);
        address1.ifEquals(address1, address2);
        address1 = address2;
        address1.ifEquals(address1, address2);
        Address address3 = new Address("Russia", "Lorina street", 32);
        System.out.println(address1.equals(address3));
        System.out.println(address1.hashCode());
        System.out.println(address3.hashCode());
    }
    void ifEquals(Address address1, Address address2) {
        if (address1 == address2) {
            System.out.println("Равны");
        } else {
            System.out.println("Не равны");
        }
    }
    private String city;
    private String street;
    private int numberOfHouse;

    public Address(String city, String street, int numberOfHouse) {
        this.city = city;
        this.street = street;
        this.numberOfHouse = numberOfHouse;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public int getNumberOfHouse() {
        return numberOfHouse;
    }

    public void setNumberOfHouse(int numberOfHouse) {
        this.numberOfHouse = numberOfHouse;
    }

//    @Override
//    public boolean equals(Object obj) {
//        if (this != obj){
//            return true;
//        }
//        if (hashCode() != obj.hashCode()) {
//            return false;
//        }
//        if (obj instanceof Address) {
//            Address address = (Address) obj;
//            return this.city.equals(address.city) && this.street.equals(address.street) && this.numberOfHouse == address.numberOfHouse;
//        } else {
//            return false;
//        }
//    }
//
//    @Override
//    public int hashCode() {
//        return city.hashCode() - street.hashCode() - numberOfHouse;
//    }

    // Autogenerated
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Address address = (Address) o;
        return numberOfHouse == address.numberOfHouse &&
                Objects.equals(city, address.city) &&
                Objects.equals(street, address.street);
    }

    @Override
    public int hashCode() {
        return Objects.hash(city, street, numberOfHouse);
    }
}

